version: "1.0"
info:
  model: int-scaffold
packages:
- name: MJANFR07NovProject
  gitServerName: SIQAGitHub
  gitUrl: https://github.com/manoj-jannu-IBM
  gitUsername: manoj-jannu-IBM
  gitBranch: main
- name: SIQAJDBCAdapterTests
  gitServerName: SIQAGitHub
  gitUrl: https://github.com/manoj-jannu-IBM
  gitUsername: manoj-jannu-IBM
  gitBranch: main
- name: SIQACloudStreamsTests
  gitServerName: SIQAGitHub
  gitUrl: https://github.com/manoj-jannu-IBM
  gitUsername: manoj-jannu-IBM
  gitBranch: main
